version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - social-media-server
    
  social-media-server:
    image: social-media-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development-build
    ports:
      - "5000:5000"
    container_name: social-media-api
    restart: always
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NODE_ENV}
